INHERIT: docs/mkdocs-base.yml

site_name: cvxrisk
site_url: https://www.cvxgrp.org/cvxrisk/
repo_url: https://github.com/cvxgrp/cvxrisk
repo_name: cvxgrp/cvxrisk

docs_dir: docs

theme:
  name: material
  logo: assets/rhiza-logo.svg
  favicon: assets/rhiza-logo.svg

nav:
  - Home: index.md
  - Notebooks: notebooks.md
  - Reports: reports.md
  - Development:
    - Marimo: development/MARIMO.md
    - Tests: development/TESTS.md
