INHERIT: docs/mkdocs-base.yml

site_name: cvxrisk
site_url: https://www.cvxgrp.org/cvxrisk/
repo_url: https://github.com/cvxgrp/cvxrisk
repo_name: cvxgrp/cvxrisk

docs_dir: docs

theme:
  name: material
  logo: assets/rhiza-logo.svg
  favicon: assets/rhiza-logo.svg

nav:
  - Home: index.md
  - Notebooks:
    - Demo: notebooks/demo.html
    - Factor Model: notebooks/factormodel.html
    - Large: notebooks/large.html
    - Sample: notebooks/sample.html
    - Tilting: notebooks/tilting.html
  - Reports:
    - Test Report: reports/html-report/report.html
    - Coverage Report: reports/html-coverage/index.html
    - Benchmark Report: reports/benchmarks/report.html
  - Development:
    - Marimo: development/MARIMO.md
    - Tests: development/TESTS.md
