name: "CI"
# Continuous Integration workflow
# This workflow runs tests across multiple operating systems and Python versions
# to ensure cross-platform compatibility.

on:
- push  # Triggered on every push to the repository

permissions:
  contents: read  # Read-only access to repository contents

jobs:
  test:
    # Cross-platform testing job
    # Tests the package on multiple operating systems and Python versions
    # to ensure compatibility across different environments
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Test on all major operating systems
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        # Test on multiple Python versions
        python-version: [ '3.12', '3.13' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.75
        with:
          python-version: ${{ matrix.python-version }}  # Use the Python version from the matrix

      - uses: tschm/cradle/actions/test@v0.1.75  # Run the test suite
