name: "CI"
# Continuous Integration workflow
# This workflow runs tests across multiple operating systems and Python versions
# to ensure cross-platform compatibility.

on:
- push  # Triggered on every push to the repository

permissions:
  contents: read  # Read-only access to repository contents

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8
        with:
          python-version: ${{ matrix.python-version }}

      - uses: cvxgrp/.github/actions/test@v2.2.8
