name: "Marimo Notebooks"
# Workflow for running marimo notebooks
# This workflow runs all marimo notebooks in the book/marimo directory in parallel
# to ensure they execute without errors.

on:
  push:  # Triggered on every push to the repository

permissions:
  contents: read  # Read-only access to repository contents

jobs:
  test:
    uses: jebel-quant/marimushka/.github/workflows/test.yml@v0.1.1
    with:
      notebook-dir: book/marimo
