name: pre-commit

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: '--verbose --all-files'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cvxgrp/.github/actions/uv/coverage@main

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          files: artifacts/tests/coverage/coverage.info
          format: lcov

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cvxgrp/.github/actions/uv/deptry@main

  deptry_uvx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/setup@main

      - name: Run deptry
        shell: bash
        run: |
          uvx deptry cvx
