name: pre-commit
# Code quality and dependency check workflow
# This workflow runs code quality checks and dependency validation
# to ensure the codebase meets standards and has no dependency issues.

permissions:
  contents: read  # Read-only access to repository contents

on:
  push:  # Triggered on every push to the repository

jobs:
  deptry:
    runs-on: ubuntu-latest

    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/deptry@v2.2.8


  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/pre-commit@v2.2.8
