name: setup

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          pip install uv

      - name: Install Dependencies
        run: |
          uv pip install -r requirements.txt --system




      - name: Set up Python
        shell: bash
        run: |
            uv python install '3.12'

      - name: Install the project
        shell: bash
        run: |
          echo $UV_PYTHON_PREFERENCE
          which python
          which pip
          uv sync --all-extras --python-preference system
